### ISSUE TITLE
Missing Font Segoe UI

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/evolve-2014-presentation-template#4]
Similar to #3, can I download this font somewhere?

![screen shot 2014-08-25 at 4 50 27 pm](https://cloud.githubusercontent.com/assets/840039/4037241/bc37b4e4-2ca1-11e4-905f-d109cc96e9e5.png)

I have the latest Keynote from the Mac App Store.

**Comment by gshackles** [comment]
There are links to download Segoe UI and Menlo on the second slide

**Comment by jonathanpeppers** [comment]
I need to start reading before posting, for others:

We are using Segoe UI for normal text.  Download Segoe UI:
https://www.dropbox.com/s/hpkow9i6398jm04/Segoe.zip

We are using Menlo for code. Download Menlo:
https://www.dropbox.com/s/c0r9812b67dy1ay/Menlo.ttc
